### ISSUE TITLE
エントロピーは小さい方が良いですか？

### ISSUE THREAD

**Issue by tom-uchida** [KotaSC/PaperSummary#2]
[DIMENSIONALITY BASED SCALE SELECTION IN 3D LIDAR POINT CLOUDS](https://github.com/KotaSC/PaperSummary/blob/master/DIMENSIONALITY%20BASED%20SCALE%20SELECTION%20IN%203D%20LIDAR%20POINT%20CLOUDS/summary.md)
の論文で，「エントロピーを最小にする」とあるけど，
基本的に，エントロピーは小さい方が良いという理解でOK？

**Comment by KotaSC** [comment]
エントロピーは小さい方が良いと思う．
「ばらつき?」が小さくなるから．
少なくとも，俺の研究の場合ではエントロピーが小さい方が精度は高くなる．
